apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: planet-frontend
  name: planet-frontend
  namespace: planet
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: planet-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: planet-frontend
    spec:
      containers:
      - image: ghcr.io/kevinmidboe/planetposen-frontend:latest
        imagePullPolicy: IfNotPresent
        name: planet-frontend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: STRIPE_API_KEY
            value: pk_test_YiU5HewgBoClZCwHdhXhTxUn
      imagePullSecrets:
        - name: ghcr-login-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

