apiVersion: v1
kind: Service
metadata:
  labels:
    app: planet-frontend
  name: planet-frontend-service
  namespace: planet
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: planet-frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
