apiVersion: v1
kind: Service
metadata:
  labels:
    app: planet-mail
  name: planet-mail-service
  namespace: planet
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: planet-mail
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
